assetDir: static
publishDir: generated
baseURL: /

DefaultContentLanguage: en
languages:
    en:
        languageName: English
        weight: 1
    nl:
        languageName: Nederlands
        weight: 2


disableHugoGeneratorInject: true
#disableLiveReload: true

enableRobotsTXT: true

permalinks:
  posts: /:year/:month/:title/

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false

markup:
  goldmark:
    renderer:
      unsafe: true
